version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.10

jobs:
  deploy:
    executor: android-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install Bundler & Fastlane plugins
          command: |
            sudo gem install bundler
            cd app
            bundle install --path vendor/bundle
      - run:
          name: Make gradlew executable
          command: chmod +x ./gradlew

      - run:
          name: Decode Keystore
          command: |
            echo $KEYSTORE_BASE64 | base64 --decode > app/keystore/my-release-key.jks
      - run:
          name: Decode Service Account JSON
          command: |
            echo $JSON_KEY_DATA | base64 --decode > app/fastlane/service-account.json
      - run:
          name: Inject Slack Webhook URL
          command: |
            if [ "$CIRCLE_BRANCH" != "develop" ] && ! git log -1 --pretty=%B | grep -qi "release"; then
              mkdir -p app/src/main/assets
              echo "SLACK_WEBHOOK_URL=$FANT_SLACK_URL" > app/src/main/assets/config.properties
              echo "✅ Slack webhook URL added."
            else
              echo "⚠️ Skipping Slack webhook URL injection (develop branch or release commit)."
            fi
      - run:
          name: Run Fastlane
          command: |
            cd app
            bundle exec fastlane deploy

workflows:
  deploy_on_branch:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
                - main 
