version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.10

jobs:
  deploy:
    executor: android-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install Fastlane
          command: |
            sudo gem install fastlane

      - run:
          name: Make gradlew executable
          command: chmod +x ./gradlew

      - run:
          name: Decode Keystore
          command: |
            echo $KEYSTORE_BASE64 | base64 --decode > app/keystore.jks

      - run:
          name: Decode Service Account JSON
          command: |
            echo $JSON_KEY_DATA | base64 --decode > app/fastlane/service-account.json

      - run:
          name: Run Fastlane
          command: |
            cd app
            fastlane deploy

workflows:
  deploy_on_develop:
    jobs:
      - deploy:
          filters:
            branches:
              only: develop
